name: Publish Package to npm

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: corepack & yarn
        run: corepack enable && yarn

      - name: build
        run: yarn build

      - name: Bump NPM version
        run: yarn version ${{github.ref_name}}

      - name: Setup .yarnrc.yml
        run: |
          yarn config set npmScopes.isimnz.npmRegistryServer "https://npm.pkg.github.com"
          yarn config set npmScopes.isimnz.npmAlwaysAuth true
          yarn config set npmScopes.isimnz.npmAuthToken ${{ secrets.NPM_TOKEN }}

      - name: Move node plugins to dist
        run: |
          mv ./gpiox_arm32.node ./dist/gpiox_arm32.node
          mv ./gpiox_arm64.node ./dist/gpiox_arm64.node

      - name: npm release
        run: yarn npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Package for Github release
        run: |
          mkdir release
          cp -r ./dist ./release/dist
          cp package.json ./release/package.json 
          zip -9 -r release-${{github.ref_name}}.zip ./release

      - name: Github release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release-${{github.ref_name}}.zip
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
